### ISSUE TITLE
Бризер Xiaomi Mi Air Purifier MJXFJ-300-G1 (добавить)

### ISSUE THREAD

**Issue by Alex-Im** [sprut/Catalog#19]
![1ud88qfhd1y8g84kkscg4cwwgcwkkw](https://user-images.githubusercontent.com/59586537/71858473-d5833f00-3104-11ea-9efd-34e690887e72.jpg)

Бризер Xiaomi Mi Air Purifier MJXFJ-300-G1
Модель: MJXFJ-300-G1
Тип устройства: Бризер
Протокол: Wi-Fi
Цвет корпуса: Белый
Расход воздуха: 300 м3/ч
Нагреватель: Да
Пл. помещения: < 105 м2
Внешняя темп.: от -30 до +50°C
Фильтр грубой очистки: Да
Фильтр тонкой очистки: Да
HEPA фильтр: Да
Угольный фильтр: Нет
Мощность нагревателя: 800 Вт
Мощность вентилятора:35 Вт
Напряжение питания: 220 В
Датчик влажности: Да
Количество скоростей: 3
Датчик загрязнения воздуха: Да
Датчик уровня CO2: Да
Датчик температуры входящего воздуха: Да
Диаметр отверстия в стене: 162 мм
Уровень шума: 24-36 дБ
Управление с мобильного: Да
Индикатор замены фильтров: Да
Совместимость с системами управления: Mi Home
Страна производства: Китай
Вес:16 кг
Габаритные размеры: 970×365×230 мм

**Comment by Batyushin** [comment]
Добавил
