### ISSUE TITLE
Aqara Wireless Mini Switch

### ISSUE THREAD

**Issue by iboolka** [sprut/Catalog#23]
На данный момент в каталоге присутствует две кнопки:
https://v2.sprut.ai/catalog/item/aqara-wireless-switch
https://v2.sprut.ai/catalog/item/aqara-wireless-switch-2

Отличием является то, что в по второй ссылке прописана модель: WXKG12LM

Необходимо:
1. Дополнить всю информацию внутри одной модели и удалить вторую
ИЛИ
2. Сделать несколько разных моделей

Что необходимо дополнить:
1. Модель: WXKG11LM
Нажатия: однократное, двукратное, трехкратное, четырехкратное

2. Модель: WXKG11LM (обновленная версия)
Нажатия: однократное, двукратное, долгое нажатие

3. Модель: WXKG12LM
Нажатия: однократное, двукратное, долгое нажатие, встряхивание (про встряхивание читал, но такой кнопки у меня нет)

Общее для всех:
1. Размер: 45 × 45 × 12 mm (1.77× 1.77 × 0.47 in.)
2. Батарея: CR2032
3. Тип устройства: Кнопка
4. Протокол: Zigbee
5. Платформа: SprutHub, deCONZ
6. Количество клавиш: Одноклавишная
7. Цвет корпуса: Белый
8. Официальная страница устройства: https://www.aqara.com/en/smart_wireless_mini_switch.html

**Comment by Batyushin** [comment]
Поправил

**Comment by Batyushin** [comment]
Задача приостановлена, т.к. пока нет возможности прикрепить некоторые параметры к типу "Кнопка".

**Comment by Batyushin** [comment]
Добавил все параметры.
