### ISSUE TITLE
Дверной замок Xiaomi Aqara N100 (добавить)

### ISSUE THREAD

**Issue by Alex-Im** [sprut/Catalog#24]
![434270_1574944625](https://user-images.githubusercontent.com/59586537/72023847-55d4ac00-328d-11ea-8c23-457b62e0b9a0.jpg)

Артикул: 964408
Бренд: Xiaomi
Производитель: Aqara
Чип безопасности Mijia / Apple
Ширина: 76 мм
Высота: 380 мм
Глубина: 25 мм
Вес: 4200 г
Диапазон рабочих температур:  -20..+70 °C
Версия Bluetooth: 5.0
Особенности: 50 отпечатков пальцев, 50 постоянных паролей, 25 NFC устройств, 25 временных паролей, 8 одноразовых временных паролей
Питание: 8 батареек типа АА
Мобильное приложение: Mi Home, Aqara Home
Сканер отпечатка пальца: Есть
Поддержка NFC: Есть
Материал корпуса: Цельнометаллический
Цвет: Черный

**Comment by Batyushin** [comment]
Добавил
