### ISSUE TITLE
Neo CoolCam 

### ISSUE THREAD

**Issue by bumer0** [sprut/Catalog#25]
Необходимо добавить:
Neo CoolCam Z-wave Light Switch EU-1 https://szneo.com/en/products/show.php?id=201
Neo CoolCam Z-wave Light Switch EU-2 https://szneo.com/en/products/show.php?id=196

Тип устройства: выключатель
Протокол: z-wave

**Comment by Batyushin** [comment]
Прошу добавить ссылки на офф сайт, и по возможности модели устройств.

**Comment by bumer0** [comment]
в первом сообщении ссылки на сайт производителя и название моделей  
обновлю на всякий случай :
Touch Switch Single  https://szneo.com/en/products/show.php?id=201 
Touch Switch Dual https://szneo.com/en/products/show.php?id=196
