### ISSUE TITLE
iTead Sonoff с прошивкой Tasmota через MQTT 

### ISSUE THREAD

**Issue by bumer0** [sprut/Catalog#26]
добавить новые устройства
Sonoff Basic с прошивкой tasmota 

+ описанные в статье https://sprut.ai/client/article/742

похоже нужна поддержка MQTT  брокер и клиент

**Comment by Batyushin** [comment]
пока мы добавляем устройства только со стоковой прошивкой, позже будет дополнение о том что возможна алтернативная прошивка и т.д.
