### ISSUE TITLE
LED Ceiling Light - есть в каталоге 1 (а в жизни 3 модели) 

### ISSUE THREAD

**Issue by bumer0** [sprut/Catalog#28]
в каталоге 1 шт
https://v2.sprut.ai/catalog/item/yeelight-led-ceiling-light-2

а в жизни 3 штуки 
огромная просьба добавить 3 модели 
все подключаются по wifi

1. Moon LED Smart Ceiling Light 450
вкл/выкл 
диммирование
цветовая температура

2. Moon LED Smart Ceiling Light 480
нет у меня, но похоже тоже самое что в 450 Moon LED Smart Ceiling Light 450
но не точно 

3. Moon LED Smart Ceiling Light 650
**основной источник света:**
вкл/выкл 
диммирование
преднастроенные режимы (Sunrise, Sunset, Nightmode, TeaTime, MovieNight, Dressing)
цветовая температура
**Дополнительный Ambilight:** 
вкл/выкл 
диммирование
RGB цвета

**Comment by Batyushin** [comment]
добавил все 3

**Comment by bumer0** [comment]
Ошибка в Moon LED Smart Ceiling Light 650
https://v2.sprut.ai/catalog/item/yeelight-led-smart-ceiling-light-650

там должно быть 2 источника света
1. основной источник света:
вкл/выкл
диммирование
преднастроенные режимы (Sunrise, Sunset, Nightmode, TeaTime, MovieNight, Dressing)
цветовая температура
2. Дополнительный Ambilight:
вкл/выкл
диммирование
RGB цвета
