### ISSUE TITLE
Device model for parameter in catalog

### ISSUE THREAD

**Issue by delonet-ai** [sprut/Catalog#36]
Можно ли добавить строку с моделью производителя, чтобы можно было ее указывать. Полезно, когда есть одинаковые устройства но разных поколений/годов с разным функционалом, пользователи сразу поймут что гуглить. 

Will be great to have a device model in description (like: MTZ0049) form official catalog or website. It will be useful for understanding same devices but with different versions or generations.

**Comment by Batyushin** [comment]
Строка с моделью добавлена
