### ISSUE TITLE
Правки в описание выключателей MiniTiger

### ISSUE THREAD

**Issue by AlexxIT** [sprut/Catalog#39]
https://v2.sprut.ai/catalog/item/minitiger-smart-wifi-wall-touch-switch

У тигра есть 433, а ещё варианты на 2 кнопки, варианты с нулём и варианты с Tuya

**Comment by Batyushin** [comment]
Если бы ты еще модели накинул, вообще бы красота была

**Comment by AlexxIT** [comment]
Приложение eWeLink пишет следующее (без нуля, прошивка ewelink/sonoff):

"brandName": "AoYan touch"

один канал
"productModel": "M601-1"
"model": "PSF-B01-GL"

два канал
"productModel": "M602-1"
"model": "PSF-B04-GL"
