### ISSUE TITLE
Aqara Relay [дополнение]

### ISSUE THREAD

**Issue by iboolka** [sprut/Catalog#42]
https://v2.sprut.ai/catalog/item/akara-relay

Добавить:

Платформа: DeCONZ
Размер: 49,3х46х24 мм
Входное напряжение: 100-250 В, 50 Гц
Максимальная нагрузка: 10А/2500 Вт

**Comment by Batyushin** [comment]
Платформу отметил, размеры и нагрузка появятся позже
