### ISSUE TITLE
GLEDOPTO CONTROLLERS

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#44]
Название: GLEDOPTO WW/CW (Warmwhite/Coldwhite) Controller
Модель: GL-C-006
Тип устройства: Led Контроллер
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 3.0
Цвет корпуса: Белый
Размер: 23.5x48x89 мм
Входное напряжение: DC12-24 V
Выходной ток/на канал: 6 A max
Общий выходной ток: 15 A max
Степень защиты: IP20
Рабочая Температура: -20°C~60°C
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-320.html
===================================================
Название: GLEDOPTO RGBW Controller
Модель: GL-C-007
Тип устройства: Led Контроллер
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 3.0
Цвет корпуса: Белый
Размер: 23.5x48x89 мм
Входное напряжение: DC12-24 V
Выходной ток/на канал: 6 A max
Общий выходной ток: 15 A max
Степень защиты: IP20
Рабочая Температура: -20°C~60°C
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-318.html
===================================================
Название: GLEDOPTO RGB+CCT Controller (УЖЕ ЕСТЬ В КАТАЛОГЕ)
Модель: GL-C-008
Тип устройства: Led Контроллер
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 3.0
Цвет корпуса: Белый
Размер: 23.5x48x89 мм
Входное напряжение: DC12-24 V
Выходной ток/на канал: 6 A max
Общий выходной ток: 15 A max
Степень защиты: IP20
Рабочая Температура: -20°C~60°C
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-303.html
===================================================
Название: GLEDOPTO LED Dimmer
Модель: GL-C-009
Тип устройства: Led Диммер
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 3.0
Цвет корпуса: Белый
Размер: 23.5x48x89 мм
Входное напряжение: DC12-24 V
Выходной ток/на канал: 6 A max
Общий выходной ток: 15 A max
Степень защиты: IP20
Рабочая Температура: -20°C~60°C
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-321.html
===================================================
Название: GLEDOPTO Mini Strip Controller
Модель: GL-C-001MC
Тип устройства: Led Контроллер
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 3.0
Цвет корпуса: Черный
Размер: 11x22x43 мм
Входное напряжение: DC 5 V
Выходной ток/на канал: 2 A max
Степень защиты: IP20
Рабочая Температура: -20°C~60°C
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-340.html

**Comment by Batyushin** [comment]
Добавил все =)
