### ISSUE TITLE
GLEDOPTO Lights

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#45]
Название: GLEDOPTO Dual White and Color LED MR16
Модель: GL-S-004Z(30°)/GL-S-005Z(120°)
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 49.5x54mm
Входное напряжение: AC 100-240V
Мощность: 4W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-339.html
=======================================
Название: GLEDOPTO Dual White and Color LED GU10
Модель: GL-S-007Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 49.5x58mm
Входное напряжение: AC 100-240V
Мощность: 5W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-322.html
=======================================
Название: GLEDOPTO Dual White and Color LED PAR16
Модель: GL-S-008Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 49.5x61mm
Входное напряжение: AC 100-240V
Мощность: 5W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-332.html
=======================================
Название: GLEDOPTO Dual White and Color LED Bulb
Модель: GL-B-007Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 57x102mm
Входное напряжение: AC 100-240V
Мощность: 6W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-326.html
=======================================
Название: GLEDOPTO Dual White and Color Candle Light Bulb
Модель: GL-B-001Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 37.5x103.5mm(E12)/37.5x110mm(E14)/
Входное напряжение: AC 100-240V
Мощность: 4W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-337.html
=================================
Название: GLEDOPTO RGB+Dual White and Color LED Bulb
Модель: GL-B-008Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 70x147mm
Входное напряжение: AC 100-240V
Мощность:12W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-323.html
=================================
Название: GLEDOPTO White and Color LED Downlight
Модель: GL-D-005Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 160x60mm
Входное напряжение: AC 100-240V
Мощность:12W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-327.html
=================================
Название: GLEDOPTO White and Color LED Downlight
Модель: GL-D-004Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 114x45mm
Входное напряжение: AC 100-240V
Мощность:9W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-328.html
=================================
Название: GLEDOPTO White and Color LED Downlight
Модель: GL-D-003Z
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 114x45mm
Входное напряжение: AC 100-240V
Мощность:6W
Zigbee Light Link (ZLL): Да
http://www.gledopto.com/h-col-333.html
=================================

**Comment by Batyushin** [comment]
Добавил. спасибо
