### ISSUE TITLE
HEIMAN Smart Metering Plug (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#46]
Название: HEIMAN Smart Metering Plug
Модель: HS2SK-E-EU
Тип устройства: Умная розетка
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Рабочее напряжение AC220V (полное напряжение)
Средняя потребляемая мощность ≤0,5 Вт
Диапазон мощности ＜3000 Вт
Диапазон напряжений 100-240В
Диапазон тока ＜16А
Размер 79.6 * 67.9*65мм 
http://www.heimantech.com/product/142.html

**Comment by Batyushin** [comment]
Добавил
