### ISSUE TITLE
HEIMAN Smoke & Carbon Monoxide Sensors (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#47]
Название: HEIMAN Smart Smoke Sensor
Модель: HS1SA-M
Тип устройства: Датчик дыма
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/89.html
====================================================
Название: HEIMAN Smart Carbon Monoxide Sensor
Модель: HS1CA-E
Тип устройства: Датчик Окиси Углерода
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/75.html

**Comment by Batyushin** [comment]
Добавил
