### ISSUE TITLE
Выключатели Lonsonho ( без 0)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#48]
Название: Lonsonho Smart Switch ( 1 клавиша, без нейтрали)
Модель: X711A-0011
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86/86/41 мм
https://aliexpress.ru/item/4000298926256.html
====================================================
Название: Lonsonho Smart Switch ( 2 клавишы, без нейтрали)
Модель: X712A-0011
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86/86/41 мм
https://aliexpress.ru/item/4000298926256.html
====================================================
Название: Lonsonho Smart Switch ( 3 клавишы, без нейтрали)
Модель: X713A-0011
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86/86/41 мм
https://aliexpress.ru/item/4000298926256.html

**Comment by Batyushin** [comment]
Спасибо, если есть возможность ссылки на официальном сайте

**Comment by GeorgyBenelli** [comment]
> Спасибо, если есть возможность ссылки на официальном сайте

Это ноунейм китайский.Сайта нет.Производится под разными брендами, но тк наши одночатовцы испытали Lonsonho на Деконз-остановился на этом бренде.Сами выключатели людям интересны.Неплохой конкурент Акаре

**Comment by Batyushin** [comment]
Добавил. Спасибо, еще бы фоток найти на белом фоне.

**Comment by droni4** [comment]
https://aliexpress.ru/item/4000369677580.html
он же, ВРОДЕ

**Comment by Batyushin** [comment]
это вроде Zemismart

**Comment by droni4** [comment]
Как писали выше, выпускают под разными брендами

**Comment by GeorgyBenelli** [comment]
> Спасибо, если есть возможность ссылки на официальном сайте

Это они.На вид с 0 и без 0 одинаковы спереди
https://www.lerlink.com/productinfo/1016824.html
https://www.lerlink.com/productinfo/1016975.html
https://www.lerlink.com/productinfo/1016978.html

**Comment by GeorgyBenelli** [comment]
> Добавил. Спасибо, еще бы фоток найти на белом фоне.

Это они.На вид с 0 и без 0 одинаковы спереди
https://www.lerlink.com/productinfo/1016824.html
https://www.lerlink.com/productinfo/1016975.html
https://www.lerlink.com/productinfo/1016978.html

**Comment by droni4** [comment]
> Добавил. Спасибо, еще бы фоток найти на белом фоне.

могу в фотошопе попробовать сделать, если не очень много резать ))) присылай на почту что нужно сделать.

**Comment by Batyushin** [comment]
Добавил спасибо
