### ISSUE TITLE
Выключатели Lonsonho ( с 0) (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#49]
Название: Lonsonho Smart Switch ( 1 клавиша )
Модель: X701A
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86*86*41 мм
https://aliexpress.ru/item/4000298926256.html
====================================================
Название: Lonsonho Smart Switch ( 2 клавишы )
Модель: X702A
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86*86*41 мм
https://aliexpress.ru/item/4000298926256.html
====================================================
Название: Lonsonho Smart Switch ( 3 клавишы )
Модель: X703A
Тип устройства: Умный выключатель
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер: 86*86*41 мм
https://aliexpress.ru/item/4000298926256.html

**Comment by Batyushin** [comment]
также добавил, очень нужны картинки

**Comment by GeorgyBenelli** [comment]
> также добавил, очень нужны картинки
Это они.На вид с 0 и без 0 одинаковы спереди
https://www.lerlink.com/productinfo/1016824.html
https://www.lerlink.com/productinfo/1016975.html
https://www.lerlink.com/productinfo/1016978.html
