### ISSUE TITLE
Trust Lights (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#50]
Название: Zigbee RGB Tunable LED Bulb RGB E27  (УЖЕ ЕСТЬ В КАТАЛОГЕ)
Модель: ZLED-RGB9
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 118x60mm
Входное напряжение: 230V
Мощность: 8.5W
Управление: Включение и выключение, Цветовая температура, Диммирование, RGB
https://www.trust.com/ru/product/71145-zigbee-rgb-tunable-led-bulb-zled-rgb9
=======================================
Название: Zigbee Dimmable LED Bulb E27  (УЖЕ ЕСТЬ В КАТАЛОГЕ)
Модель: ZLED-2709
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 110x60mm
Входное напряжение: 230V
Мощность: 9W
Управление: Включение и выключение, Диммирование
Zigbee Light Link (ZLL): Да
https://www.trust.com/ru/product/71155-zigbee-dimmable-led-bulb-zled-2709
=======================================
Название: Zigbee Dimmable LED Bulb Flame E27
Модель: ZLED-2209
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 110x60mm
Входное напряжение: 230V
Мощность: 9W
Управление: Включение и выключение, Диммирование
Zigbee Light Link (ZLL): Да
https://www.trust.com/ru/product/71179-zigbee-dimmable-led-bulb-flame-zled-2209
=======================================
Название: Zigbee Tunable LED Bulb E27
Модель: ZLED-TUNE9
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 110x60mm
Входное напряжение: 230V
Мощность: 9W
Управление: Включение и выключение, Диммирование
Zigbee Light Link (ZLL): Да
https://www.trust.com/ru/product/71156-zigbee-tunable-led-bulb-zled-tune9
=======================================
Название: Zigbee Dimmable LED Bulb E14
Модель: ZLED-EC2206
Тип устройства: Led Лампа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 109x37mm
Входное напряжение: 230V
Мощность: 6W
Управление: Включение и выключение, Диммирование
Zigbee Light Link (ZLL): Да
https://www.trust.com/ru/product/71160-zigbee-dimmable-led-bulb-zled-ec2206
=======================================
Название: Zigbee Remote Control
Модель: ZYCT-202
Тип устройства: Пульт управления
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
Размер: 115x70x15mm
Управление: Включение и выключение, Диммирование
https://www.trust.com/ru/product/71171-zigbee-remote-control-zyct-202
=======================================

**Comment by Batyushin** [comment]
Перенес
