### ISSUE TITLE
Trust Sensors (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#51]
Название: Zigbee Wireless Motion Sensor
Модель: ZPIR-8000
Тип устройства: Датчик движения
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
https://www.trust.com/en/product/71170-zigbee-wireless-motion-sensor-zpir-8000
=======================================
Название: Zigbee Wireless Contact Sensor
Модель: ZCTS-808
Тип устройства: Датчик касания
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
https://www.trust.com/ru/product/71169-zigbee-wireless-contact-sensor-zcts-808
=======================================

**Comment by Batyushin** [comment]
Спасибо, добавил =)
