### ISSUE TITLE
Heiman Sensors (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#52]
Название: Heiman Motion Sensor
Модель: HS1MS
Тип устройства: Датчик движения
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/93.html
=======================================
Название: Heiman Smart Door Sensor
Модель: HS1DS
Тип устройства: Датчик касания
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/83.html
=======================================
Название: Heiman Smart Temperature and Humidity Sensor
Модель: HS1HT
Тип устройства: Датчик температуры и влажности
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/86.html
=======================================
Название: Heiman Smart Combustible Gas Sensor
Модель: HS1CG
Тип устройства: Датчик горючего газа
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/76.html
=======================================
Название: Heiman Smart Water Leakage Sensor
Модель: HS1WL
Тип устройства: Датчик утечки
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/100.html
=======================================
Название: Heiman Smart Wireless Siren
Модель: HS2WD-E
Тип устройства: Сирена
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
http://www.heimantech.com/product/153.html
=======================================

**Comment by Batyushin** [comment]
Перенес. Спасибо
