### ISSUE TITLE
BOSCH Pro-Grade motion sensor (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#54]
Название: BOSCH Pro-Grade motion sensor
Модель: ISW-ZPR1-WP13 
Тип устройства: Датчик движения
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee 
Цвет корпуса: Белый
https://www.boschsecurity.com/de/de/produkte/einbruchmeldeanlagen/tritech-bewegungsmelder/

http://resource.boschsecurity.com/documents/Bosch_ZigBee_Wireles_Data_sheet_enUS_14786372619.pdf

**Comment by Batyushin** [comment]
Добавил
