### ISSUE TITLE
Centralite Zigbee Devices (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#55]
Название: Centralite Motion Sensor
Модель: 3305-G
Тип устройства: Датчик движения
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee 
Цвет корпуса: Белый
https://centralite.com/products/motion-sensor
=======================================

**Comment by Batyushin** [comment]
Добавил
