### ISSUE TITLE
Eurotronic Spirit Zigbee Thermostat (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#56]
Название: Eurotronic Spirit Zigbee Thermostat
Модель: SPZB0001
Тип устройства: Термостат
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee
Цвет корпуса: Белый
Размер: 56x68x89мм
Напряжение питания: 2 x 1.5 V AA/Mignon/LR6
Диапазон регулировки: от 5° C до 30° C
https://eurotronic.org/produkte/zigbee-heizkoerperthermostat/spirit-zigbee/

**Comment by Batyushin** [comment]
Добавил
