### ISSUE TITLE
Shelly Dimmer (Добавить устройство)

### ISSUE THREAD

**Issue by macros0** [sprut/Catalog#57]
Название: Shelly Dimmer
Модель: Shelly Dimmer
Тип устройства: Реле
Платформа: Shelly Cloud
Протокол: wifi
Цвет корпуса: Белый
Размер: 91x43x25мм
Входное напряжение: 110-230V ±10%, 50/60Hz
Вход (max): AC 110-230V ±10%, 50/60Hz
Выход (max): AC 110-230V ±10%, 50/60Hz
https://shop.shelly.cloud/shelly-dimmer-wifi-smart-home-automation#58

**Comment by macros0** [comment]
Размеры проморгал: 42mm x 36mm x 14 mm
Тип устройства: наверное Силовой блок

**Comment by Batyushin** [comment]
Добавил
