### ISSUE TITLE
Philips Hue Tap Switch (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#58]
Название: Philips Hue Tap Switch
Модель: PTM215Z
Тип устройства: Пульт
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee
Цвет корпуса: Белый
Диаметр: 75мм
Высота: 25мм
Zigbee Light Link (ZLL): Да
https://www2.meethue.com/en-us/p/hue-tap-switch/046677473365

**Comment by Batyushin** [comment]
Добавил
