### ISSUE TITLE
Lifecontrol MCLH-03

### ISSUE THREAD

**Issue by macros0** [sprut/Catalog#59]
Название: Lifecontrol Умная розетка
Модель:MCLH-03
Тип устройства: Умная розетка
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ, zigbee2mqtt
Протокол: Zigbee
Цвет корпуса: Белый/Черный
Рабочее напряжение 90-245 В / 50–60 Гц
Ток потребления: 10 мкА в дежурном режиме, 40 мА в режиме управления
Диапазон мощности ＜2000 Вт
Диапазон напряжений 100-240В
Диапазон тока ＜10А
Размер  7,7×6,2 см, вес 75 грамм
https://lifecontrol.ru/devices/smart-plug/

**Comment by Batyushin** [comment]
Спасибо добавил https://v2.sprut.ai/catalog/item/lifecontrol-umnaa-rozetka
