### ISSUE TITLE
Philips Hue Outdoor sensor (Добавить устройство)

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#60]
Название: Philips Hue Outdoor sensor
Модель: SML002
Тип устройства: Наружный датчик движения
Платформа: Home Assistant, Homebridge, NodeRED, deCONZ
Протокол: Zigbee
Цвет корпуса: Черный
Пылевлагозащита: IP54
Ширина: 76мм
Высота: 76мм
Глубина: 56мм
https://www2.meethue.com/en-us/p/hue-outdoor-sensor/046677541736#

Пока еще не в белом списке Деконз но работает с ним.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1201

**Comment by Batyushin** [comment]
Добавил
