### ISSUE TITLE
Модуль реле DRM88R v2 Модуль релейный, 8 входов и 8 выходов реле

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#65]
Модель:  DRM88R v2
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 8
Цвет корпуса: Белый
Управление: Включение и выключение
https://razumdom.ru/catalog/modbus_rtu/rele_rtu_rs485/744/

**Comment by Batyushin** [comment]
Добавил
