### ISSUE TITLE
DRM88RL Модуль релейный, 8 входов и 8 каналов реле по 16А

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#66]
Модель:  DRM88RL
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 8
Цвет корпуса: Белый
Управление: Включение и выключение
https://razumdom.ru/catalog/modbus_rtu/rele_rtu_rs485/671/

**Comment by Batyushin** [comment]
Добавил =)
