### ISSUE TITLE
DRM21R Модуль релейный, 2 входа, 1 выход реле 30А

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#67]
Модель: DRM21R
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 2
Цвет корпуса: Белый
https://razumdom.ru/catalog/modbus_rtu/rele_rtu_rs485/717/
Управление: Включение и выключение

**Comment by Batyushin** [comment]
Добавил
