### ISSUE TITLE
DDM845R v3 Модуль диммерный 4х канальный транзисторный. Нагрузка 500 Вт на канал

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#68]
Модель: DDM845R v3
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 4
Цвет корпуса: Белый
https://razumdom.ru/catalog/modbus_rtu/dimmery_rtu_rs485/507/
Управление: Диммирование

**Comment by Batyushin** [comment]
Добавил
