### ISSUE TITLE
DDM8410R v3 Модуль диммерный 4х канальный транзисторный. Нагрузка 1000 Вт на канал

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#69]
Модель: DDM8410R v3
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 4
Цвет корпуса: Белый
Управление: Диммирование
https://razumdom.ru/catalog/modbus_rtu/dimmery_rtu_rs485/508/

**Comment by Batyushin** [comment]
Добавил
