### ISSUE TITLE
неверное название устройства yeelight strip

### ISSUE THREAD

**Issue by akurach** [sprut/Catalog#7]
<img width="818" alt="Screenshot 2020-01-07 at 00 54 51" src="https://user-images.githubusercontent.com/1264049/71851816-6f88be80-30e8-11ea-8814-8c9185fb0d37.png">
https://v2.sprut.ai/catalog/item/yeelight-led-desk-lamp### 

правильное название Aurora Lightstrip Plus(color)

**Comment by Batyushin** [comment]
> <img alt="Screenshot 2020-01-07 at 00 54 51" width="818" src="https://user-images.githubusercontent.com/1264049/71851816-6f88be80-30e8-11ea-8814-8c9185fb0d37.png">
> 
> https://v2.sprut.ai/catalog/item/yeelight-led-desk-lamp###
> правильное название Aurora Lightstrip Plus(color)

Поправил, спасибо
