### ISSUE TITLE
DDL04R: 4х канальный диммер PWM LED RGBW и 4х канальный регулятор 0-10 В.

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#70]
Модель: DDL04R
Тип устройства: Оборудование на DIN рейку
Протокол: modbus rs-485 rs485
Наличие нуля: С нулевой линией
Количество каналов: 4
Цвет корпуса: Белый
Управление: Диммирование, RGB+W или RGBW 
https://razumdom.ru/catalog/modbus_rtu/dimmery_rtu_rs485/762/

**Comment by Batyushin** [comment]
Добавил
