### ISSUE TITLE
MSU44RHT Датчик температуры и влажности

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#71]
Модель: MSU44RHT
Тип устройства: Датчик
Тип датчика: Датчик температуры и влажности
Протокол: modbus rs-485 rs485
Цвет корпуса: Белый
https://razumdom.ru/catalog/modbus_rtu/datchiki_rtu_rs485/768/

**Comment by Batyushin** [comment]
На сайте производителя картинки не того датчика, нужны картинки
