### ISSUE TITLE
Датчик MSU44RHTLP температуры, влажности, освещенности, давления

### ISSUE THREAD

**Issue by Ziracul** [sprut/Catalog#74]
Модель: Датчик MSU44RHTLP 
Тип устройства: Датчик
Тип датчика: Датчик температуры, влажности, освещенности, давления
Протокол: modbus rs-485 rs485
Цвет корпуса: Белый
https://razumdom.ru/catalog/modbus_rtu/datchiki_rtu_rs485/772/

**Comment by Batyushin** [comment]
Нужны качественные картинки
