### ISSUE TITLE
DOOYA мотор DT82TV (Добавить устройство)

### ISSUE THREAD

**Issue by droni4** [sprut/Catalog#76]
Название: Электро карниз DOOYA
Модель:DT82TV
Тип устройства: Умный электро карниз
Платформа:
Протокол: 443Mhz, RS-485, сухие контакты, 220В
Цвет корпуса: Белый
Входное напряжение: 100-240 V 50/60Hz
Размер:  мм

**Comment by droni4** [comment]
https://aliexpress.ru/item/32634582958.html

**Comment by Batyushin** [comment]
Добавил, официального сайте у них нет?

**Comment by droni4** [comment]
Сайта не видел очень давно, если найду добавлю дополнительно

**Comment by Batyushin** [comment]
спасибо
