### ISSUE TITLE
Shelly 2.5 [Добавить устройство]

### ISSUE THREAD

**Issue by iboolka** [sprut/Catalog#83]
Тип устройства: Силовой блок, Рулонная штора
Платформа: Home Assistant, Homebridge
Протокол: Wi-Fi
Наличие нуля: С нулевой линией
Цвет корпуса: Черный
Управление: Включение и выключение, Вращение по нажатию
Частота: 2.4 ГГЦ (802.11 b/g/n)
Размер: 39 x 36 x 17 (mm)
Количество каналов: 2
Поддержка выключателя/переключателя: да
Питание: 110-230V ±10, 50/60Hz AC 
Максимальная нагрузка: 10A / 230V 50/60Hz
Оф. сайт: https://shelly.cloud/shelly-25-wifi-smart-relay-roller-shutter-home-automation/
Изображение: https://shelly.cloud/wp-content/uploads/2019/01/shelly-25.png

**Comment by Batyushin** [comment]
Спасибо добавил
