### ISSUE TITLE
Ubiquiti UniFi Video G3-FLEX [Добавить устройство]

### ISSUE THREAD

**Issue by iboolka** [sprut/Catalog#84]
Производитель: Ubiquiti
Модель: UVC G3 Flex
Размеры: Ø 107.5 x 48 x 48 мм
Вес: 170 г
Сетевой интерфейс: 1х 10/100 Ethernet
Матрица: 1/2.7" 2-Megapixel HDR Sensor
Объектив: EFL 3.4mm / f1.2
Ночной режим: Инфракрасная LED-подсветка с механическим ИК-фильтром
Микрофон: Да
Способ питания: 802.3af PoE
Питания: 802.3af PoE Switch Port
Максимальная потребляемая мощность: 4 Вт
Крепление: Table, Wall (Indoor/Outdoor), Pole
Рабочая температура: -20.. 50 °C
Рабочая влажность: 20.. 90 % без конденсата
Стандарт сжатия: H.264
Разрешение: 1080p Full HD (1920x1080)
Максимальная частота кадров в секунду: 25 FPS
Поддержка потокового видео: Да, RTSP
Интеграция: HomeBridge
Сайт производителя: https://unifi-protect.ui.com/g3-flex
Фото камеры: https://cdn.shopify.com/s/files/1/1439/1668/products/UVC-G3-FLEX_Front_Angle_1024x1024.png?v=1561508041

**Comment by Batyushin** [comment]
Добавил=)
