### ISSUE TITLE
Добавить атрибут поддерживаемых протоколов (RTSP\ONVIF) для камер

### ISSUE THREAD

**Issue by MrR1p** [sprut/Catalog#85]
Можно добавить атрибут для камер - поддерживают ли они какие-либо протоколы (RTSP например). Накидал несколько камер, которые знаю и способ получения потока, если его нет из коробки (возможно тоже будет полезно)

Aqara
- Camera Hub G2H
    нет потока
- Camera Hub G2
    нет потока
- Camera Hub
    нет потока

Xiaomi
- Mi Home Security Camera 360°
    Можно получить RTSP поток для камеры с моделью MJSXJ02CM через хак
    https://github.com/telmomarques/xiaomi-360-1080p-hacks
- Xiaomi Dafang
    Можно получить RTSP поток для камеры с процессором T20 через хак
    https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

HUALAI
- iSmartAlarm Spot Plus Camera 
    нет достоверных данных, что можно получить поток
- DaFang SMART CAMERA (Но вроде они выпускаются под брендом xiaomi)
    Можно получить RTSP поток для камеры с процессором T20 через хак
    https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks
- XiaoFang SMART CAMERA (Но вроде они выпускаются под брендом xiaomi)
    Можно получить RTSP поток для камеры с процессором T20 через хак
    https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

Wyze
- Wyzecam Pan
    Можно получить RTSP поток либо через официальную перепрошивку (но это бета), либо через хак:
    https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks
- Wyzecam V2
    Можно получить RTSP поток либо через официальную перепрошивку (но это бета), либо через хак:
    https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

Yi
- Yi Home 17CN / 27US / 47US
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4
    Или с помощью других хаков в зависимости от модели (что-то не осилил, так как их вагон и маленькая тележка)
- Yi 1080p Home
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4
- Yi Dome
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4
- Yi 1080p Dome
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4
- Yi 1080p Cloud Dome
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4
- Yi 1080p Outdoor
    Можно получить RTSP поток для камеры через хак (но функция RTSP платная - 3 фунта):
    https://github.com/TheCrypt0/yi-hack-v4

Reolink:
- Все камеры из коробки поддерживают RTSP

Digma:
 - Digma division 100
    RTSP и ONVIFиз коробки
    Остальные модели тоже возможно, но их нужно тестировать, не уверен

**Comment by Batyushin** [comment]
Добавил протоколы, дополнил устройства

**Comment by MrR1p** [comment]
Может в материалы или вопрос/ответ добавить ссылки на прошивки/хаки?
