### ISSUE TITLE
Применение фильтра по типам устройства прямо из карточки устройства

### ISSUE THREAD

**Issue by delonet-ai** [sprut/Catalog#88]
Вариант применения фильтра сразу с результатам и по категории. Удобно, когда выбираешь из нескольких устройств, чтобы показать все устройства данного типа. 
Два скриншота, ссылка при нажатии и результат с заполненным фильтром.

<img width="1257" alt="Screenshot 2020-03-30 at 00 23 00" src="https://user-images.githubusercontent.com/58390790/77861371-46765680-721d-11ea-956f-fc3b53e47925.png">

<img width="1246" alt="Screenshot 2020-03-30 at 00 26 30" src="https://user-images.githubusercontent.com/58390790/77861376-4fffbe80-721d-11ea-9613-27a0844ec834.png">

**Comment by olddeda** [comment]
Держите )

https://www.icloud.com/photos/#08hO42TagDe-aGriohV3SCDSQ
