### ISSUE TITLE
Smarter iKettle 3rd Generation [Добавить устройство]

### ISSUE THREAD

**Issue by GeorgyBenelli** [sprut/Catalog#89]
Название: iKettle 3.0
Тип устройства: Умный чайник
Платформа: IFTTT, Homebridge, NodeRED, ioBroker
Протокол: Wi-Fi
Сайт: https://www.smarter.am/ikettle

**Comment by Batyushin** [comment]
Добавил, жду отзыв от устройстве https://v2.sprut.ai/catalog/item/smarter-ikettle-3rd-generation
